### ISSUE TITLE
Update API to return new subject level results

### ISSUE THREAD

**Issue by surchs** [neurobagel/api#112]
- in models.py, add to CohortQueryResponse data model:
  - [x] `dataset_portal_uri`
  - [x] `dataset_file_path`
- update query string to return from graph, in addition to existing variables:
  - [x] dataset PortalURI (using `hasPortalURI`)
  - [x] dataset FilePath (using `hasFilePath`)
  - [x] SessionID (using `hasLabel`)
- remove `dataset` (i.e., unique dataset identifier, `https://iri.nidash...`) and `subject` IRIs from returned variables in query string
- in crud.py, when constructing `subject_data` dataframe from graph-returned data:
  - [x] remove `dataset_name` for each subject entry
  - [x] group acquisitions by subject and session such that each row is a subject-session, and `diagnosis` and `modality` become lists

**Comment by surchs** [comment]
I updated the OpenNeuro graph as part of https://github.com/neurobagel/project/issues/123

**Comment by alyssadai** [comment]
Updated the spec, anything else I missed @rmanaem?

Also, @surchs I realized there are two additional variables that are returned in the current implementation of unaggregated results, which I think we forgot about when creating the sample query tool csvs in https://github.com/neurobagel/project/issues/119. These are `num_sessions` at the subject level, and `image_modals` (list of unique image modalities) at the dataset level.

Since the query tool UI provides the `image_modals` as little icons per matching dataset, I think we should still keep this in the 'raw' API result as well (it would go in the dataset-level output csv). I think `num_sessions` would also be a useful variable to keep per subject-session row in the subject-level output csv, so that a user could verify the results for a query for a specific minimum # sessions.

Thoughts?

**Comment by surchs** [comment]
> These are num_sessions at the subject level, 

Agreed, this would be good

> and image_modals (list of unique image modalities) at the dataset level.

Also agreed. We have them at the subject level already: https://github.com/neurobagel/documentation/wiki/Query-Tool#example-data. So now we would create the set of all `image_modals` across all subjects and sessions and provide that in the `dataset.csv`, correct? If so: please go ahead and update the wiki to reflect the new output goal - and then add the link to the wiki to the spec of this issue and the query-tool one: https://github.com/neurobagel/query-tool/issues/76 as reference.

**Comment by rmanaem** [comment]
> remove `dataset` (i.e., unique dataset identifier, https://iri.nidash...) and `subject` IRIs from returned variables in query string

@alyssadai What is the `subject` IRI here? Isn't it the `subject ID`?

**Comment by surchs** [comment]
Are we done spec-ing this? Does it need breaking up further? Otherwise I'd say let's get started so we don't block other stuff

**Comment by rmanaem** [comment]
After discussion, this is what the API should return upon implementation of this issue:

```json
[
    {
        "dataset_name": "Longitudinal Brain Correlates of Multisensory Lexical Processing in Children",
        "dataset_portal_uri": "https://openneuro.org/datasets/ds002725",
        "dataset_file_path": "https://github.com/OpenNeuroDatasets/ds002725.git",
        "num_matching_subjects": 55,
        "subject_data": [
          {  
            // subject-session dict
            "sub_id": "sub-021",
            "session_id": "ses-pre",
            "num_sessions": "2",
            "age": "10.21",
            "sex": "http://purl.bioontology.org/ontology/SNOMEDCT/248153007",
            "diagnosis": [null],
            "subject_group": null,
            "assessment": null,
            "image_modal": ["http://purl.org/nidash/nidm#FlowWeighted", "http://purl.org/nidash/nidm#T1Weighted"],
            "file_path": null,
          }
        ]
    }
]   
```
