### ISSUE TITLE
Q: API Security Model

### ISSUE THREAD

**Issue by gdevenyi** [neurobagel/api#123]
If the API itself doesn't have any security, one can run any query, what is the point of the DBUser restricting access to the graph DB? Why not just use the anonymous user stardog automatically sets up?

https://docs.stardog.com/operating-stardog/security/security-model#default-security-configuration

**Comment by surchs** [comment]
Hey @gdevenyi, you're right that stardog creates an anonymous user by default, but that user has no permissions. We explicitly create a separate user with specific credentials in the graph so that anonymous users cannot send requests to the graph. 

There are two other aspects here that are going to be implemented:
1. We will completely remove direct access to the graph API so that all requests  need to go through the neurobagel API that creates SPARQL queries. The remaining blocker for that is that the neurobagel API then needs to provide an endpoint to add data to the graph - which it does not yet. 
2. Requests to the neurobagel API don't require credentials, because these requests cannot run specific SPARQL queries but only query pre-validated query parameters. This also means that every user is treated the same by the API, and the response granularity has to be such that it is appropriate for the least privileged user. In the future we will provide authentication against the neurobagel API. However this needs to be done in a way that can work in a federated context, so that's something we'll discuss a bit more.

In the meantime I'll close this issue.
