### ISSUE TITLE
[ENH] Change default setting to return subject-level attributes (?)

### ISSUE THREAD

**Issue by FPa-riken** [neurobagel/api#200]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### New feature

The default setting prevents returning actual subject-level attributes values in the query result.

As a newbie that has just deployed Neurobagel locally, it took me some time to figure out why all returned values are changed to "protected".
So I'd suggest to either change the default setting, or make it clearer in the documentation that one needs to change it to get actual subject-level attributes values when querying.

---

`NB_RETURN_AGG` is `true` by default :

https://github.com/neurobagel/api/blob/d63d262b2a37fba3a2ee451c9705d20bda036133/docs/api_environment_variables.tsv?plain=1#L6

https://github.com/neurobagel/api/blob/d63d262b2a37fba3a2ee451c9705d20bda036133/.template-env?plain=1#L6

https://github.com/neurobagel/api/blob/d63d262b2a37fba3a2ee451c9705d20bda036133/docker-compose.yml#L14

**Comment by surchs** [comment]
Thanks a lot for the feedback @FPa-riken and welcome to neurobagel!

**Comment by alyssadai** [comment]
Hey @FPa-riken, thanks for the feature/documentation request.

Indeed, the API is configured to return only aggregate results from the graph by default because we want deploying users to purposefully decide to expose identifying subject-level info to queries (to avoid unintentionally breaching data sharing agreements for more protected datasets).

That said, we agree that this behaviour could be more clearly documented. We recently merged a [PR](https://github.com/neurobagel/documentation/pull/105/files) in the documentation that seeks to clarify exactly this (the default aggregate mode + how to change visibility of the 'protected' values). You can also see the new section on our deployed docs [here](https://neurobagel.org/query_tool/#protected-participant-level-results-in-aggregate-mode)).

If these changes sufficiently address your feedback, please feel free to close the issue (or let us know if not).

**Comment by FPa-riken** [comment]
Hi @alyssadai,

I think the updated documentation should be enough. 
Even though the explanation was not added in the page followed when [setting up a graph](https://neurobagel.org/infrastructure), now a simple search of the text `protected` in the documentation UI returns the paragraph that makes all clear.
Thanks.
