### ISSUE TITLE
Deploy API in Docker container on cloud server

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/api#78]
- [x] Ensure that the dockerized API can connect to the graph locally
  - the connection should happen inside the server. So either directly from docker API to graph on the same machine or
  - within a shared docker network between docker API and docker graph
- [x] #86
- [x] #87

**Comment by alyssadai** [comment]
The graph container and API container (0.1.0) have been added to the same Docker bridge network (`nb-net`) on the cloud server. The API currently sends requests to the graph using its network alias, `sdgraph`.

**Comment by surchs** [comment]
@alyssadai: this seems to have turned into an epic / bigger issue. Since you addressed 1/3, how about we either
- close this guy and address the remaining two open issues (#86 and #87) later
- turn this guy into an epic and take it out of "Doing" / unassign you to have a place to track all this if that is needed
